FROM ubuntu

MAINTAINER niko <ngardzie@student.hive.fi>

RUN apt-get update && apt-get upgrade -y && apt install -y wget openjdk-11-jdk

RUN wget https://launcher.mojang.com/v1/objects/bb2b6b1aefcd70dfd1892149ac3a215f6c636b07/server.jar

RUN java -Xmx1024M -Xms1024M -jar server.jar nogui

RUN echo "eula=true" > eula.txt

ENTRYPOINT java -Xmx1024M -Xms1024M -jar server.jar nogui